eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: false
  instance:
    #hostname: localhost
    preferIpAddress: true
    #ipAddr: 127.0.0.1
    
    # O servidor espera pulsações do cliente em um intervalo configurado com esta propriedade - o valor padrão é 30
    lease-renewal-interval-in-seconds: 30

microservice:
  auth-api:
    endpoints:
      endpoint:
        uri: http://AUTH-API/auth
  cliente-api:
    endpoints:
      endpoint:
        uri: http://CLIENTE-API/cliente
