eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservice:
  auth-api:
    endpoints:
      endpoint:
        uri: http://AUTH-API/auth
  cliente-api:
    endpoints:
      endpoint:
        uri: http://CLIENTE-API/cliente
